
export default function getAllContent() {
    return [
      {
        id: 'CONTENT-1',
        slug: 'menulis_cv_yang_menarik',
        title: "Menulis CV yang Menarik",
        instructor: 'Tiara Dewi',
        videoCount: 3,
        rating: 4.9,
        Categori : `CV`,
        image: '/src/assets/elearning 1.png',
        video1: `https://youtu.be/tHQXZJ2f00Y?si=uwoiY87doHYidw5O`,
        video2: `https://youtu.be/M5iPwArwOoU?si=n6yoyukqf57xSd-g`,
        video3: `https://youtu.be/HoAG5PEpKaE?si=mhvdxpa1CVhxxWL_`,
        content1:`Apa itu CV dan kenapa penting?`,
        content2:`Cara menonjolkan pengalaman dan keahlian`,
        content3:`Menyesuaikan CV dengan pekerjaan yang dilamar`,
        description: `Pelajari cara membuat CV yang menonjolkan keahlian dan pengalamanmu secara efektif, serta menyesuaikannya dengan pekerjaan yang ingin kamu lamar.`
      },
      {
        id: 'CONTENT-2',
        slug: 'struktur_cv_yang_efektif',
        title: "Struktur CV yang Efektif",
        instructor: 'Siska larasati',
        videoCount: 3,
        rating: 5,
        Categori : `CV`,
        image: '/src/assets/elearning 2.png',
        video1: `https://youtu.be/ZUAQ3bATGKI?si=nBFbi71fhKDdu7LG`,
        video2: `https://youtube.com/shorts/MROnKsRbNDw?si=H8986a3hr7-3AbwN`,
        video3: `https://youtube.com/shorts/BSLT-hZIY1A?si=hz3sLiZrFkHFazQK`,
        content1:`Format dasar CV: urutan dan isi`,
        content2:`Tips menulis ringkasan diri (summary) yang menarik`,
        content3:`Contoh CV untuk berbagai bidang pekerjaan`,
        description: `Dapatkan panduan tentang susunan CV yang tepat, termasuk tips menulis ringkasan diri yang menarik serta contoh-contoh CV sesuai bidang pekerjaan.`
      },      
      {
        id: 'CONTENT-3',
        slug: 'membangun_portfolio_profesional',
        title: "Membangun Portfolio Profesional",
        instructor: 'Maya Putri',
        videoCount: 3,
        rating: 4.9,
        Categori : `Portfolio`,
        image: '/src/assets/elearning 3.png',
        video1: `https://youtu.be/2TgDkN_NFdA?si=cWUbTrV6QicwFNsT`,
        video2: `https://youtube.com/shorts/fkVudzkKsDU?si=i03M1xvfbkBpM-ya`,
        video3: `https://youtube.com/shorts/sXWpXHtyvRs?si=ps_oR2pk_Mhj8aqX`,
        content1:`Apa itu portfolio dan kegunaannya?`,
        content2:`Proyek dan pengalaman yang perlu dimasukkan`,
        content3:`Contoh-contoh portfolio yang efektif`,
        description: `Pelajari cara menyusun portfolio yang mencakup proyek dan pengalaman terbaik, sehingga memperlihatkan keahlianmu secara maksimal.`
      },      
      {
        id: 'CONTENT-4',
        slug: 'menyesuaikan_portfolio_untuk_pekerjaan',
        title: "Menyesuaikan Portfolio untuk Pekerjaan",
        instructor: 'Raka Nugraha',
        videoCount: 3,
        rating: 4.6,
        Categori : `Portfolio`,
        image: '/src/assets/elearning 4.png',
        video1: `https://youtu.be/SqUFC4R_vpM?si=AlcxqpXrUSK6O6Me`,
        video2: `https://youtube.com/shorts/9WDUCVz8inY?si=zwRcZXwdbK1VAzTx`,
        video3: `https://youtube.com/shorts/Oy7P1tprapg?si=3hED1XDwo7C3bw-d`,
        content1:`Membuat portfolio sesuai dengan posisi yang dilamar`,
        content2:`Cara menunjukkan skill utama di portfolio`,
        content3:`Contoh penyesuaian portfolio untuk bidang kreatif vs. non-kreatif`,
        description: `Ketahui cara menyesuaikan portfolio sesuai dengan pekerjaan yang dilamar, sehingga mampu menunjukkan keahlian yang relevan dan spesifik.`
      },
      {
        id: 'CONTENT-5',
        slug: 'persiapan_sebelum_interview',
        title: "Persiapan Sebelum Interview",
        instructor: 'Rian Utama',
        videoCount: 3,
        rating: 4.8,
        Categori : `Interview`,
        image: '/src/assets/elearning 5.png',
        video1: `https://youtu.be/Ka-fFbEFDaw?si=p8BhDk7bU_BVQLWy`,
        video2: `https://youtube.com/shorts/S-0vhN7SVKQ?si=6tagpvAiZ9dSss6P`,
        video3: `https://youtu.be/-kG4I4F9oMw?si=e3ciJiNJQgBXniR_`,
        content1:`Riset tentang perusahaan dan posisi`,
        content2:`Menyiapkan jawaban untuk pertanyaan umum`,
        content3:`Membuat daftar pertanyaan untuk pewawancara`,
        description: `Lakukan riset dan persiapan awal agar lebih siap menghadapi interview, termasuk menyiapkan jawaban untuk pertanyaan umum serta daftar pertanyaan untuk pewawancara.`
      }, 
      {
        id: 'CONTENT-6',
        slug: 'menguasai_teknik_menjawab_pertanyaan',
        title: "Menguasai Teknik Menjawab Pertanyaan",
        instructor: 'Nadia Kurnia',
        videoCount: 3,
        rating: 4.7,
        Categori : `Interview`,
        image: '/src/assets/elearning 6.png',
        video1: `https://youtu.be/JZBjCA5Z19c?si=Z9kSmjthxOY8ZAXx`,
        video2: `https://youtube.com/shorts/tNyNm1HnQx4?si=CCgCjCevRCPDCUtC`,
        video3: `https://youtube.com/shorts/HrEIsD7MsHM?si=0C58nNmffXg9kcK9`,
        content1:`Teknik STAR (Situation, Task, Action, Result) untuk menjawab pertanyaan`,
        content2:`Tips menjawab pertanyaan sulit dan situasional`,
        content3:`Contoh jawaban untuk pertanyaan umum seperti “Ceritakan tentang diri Anda`,
        description: `Pelajari teknik-teknik menjawab pertanyaan seperti metode STAR dan tips menjawab pertanyaan sulit dengan percaya diri.`
      }, 
      {
        id: 'CONTENT-7',
        slug: 'membangun_kesan_yang_baik_saat_interview',
        title: "Membangun Kesan yang Baik Saat Interview",
        instructor: 'Rian Utama',
        videoCount: 3,
        rating: 4.9,
        Categori : `Interview`,
        image: '/src/assets/elearning 7.png',
        video1: `https://youtu.be/aLaGDL_DnKs?si=O4A88IYIOEJWoI4f`,
        video2: `https://youtube.com/shorts/apY5NjA6_zM?si=5s990z464YhVWpiO`,
        video3: `https://youtube.com/shorts/DtUoOeBTamI?si=TlOfuJDBDASO3tem`,
        content1:`Tips bahasa tubuh yang positif`,
        content2:`Cara menunjukkan antusiasme dan profesionalisme`,
        content3:`Mengatasi gugup saat interview`,
        description: `Ketahui cara memberikan kesan profesional, mulai dari bahasa tubuh hingga mengatasi rasa gugup agar tampil lebih percaya diri.`
      }, 
      {
        id: 'CONTENT-8',
        slug: 'desain_portfolio_yang_menarik',
        title: "Desain Portfolio yang Menarik",
        instructor: 'Nadia Kurnia',
        videoCount: 3,
        rating: 4.9,
        Categori : `Portfolio`,
        image: '/src/assets/elearning 8.png',
        video1: `https://youtu.be/BuhhV5qDki8?si=FT-lIeXiZ9VIg8Gq`,
        video2: `https://youtube.com/shorts/otGmGbrzwy0?si=bb1bEUCYAULHhwvH`,
        video3: `https://youtu.be/4EVLbnOkHw8?si=QQIHy41ZJQOXl5rh`,
        content1:`Pemilihan layout dan tampilan`,
        content2:`Menampilkan hasil kerja terbaik`,
        content3:`Platform digital untuk membangun portfolio online`,
        description: `Temukan tips desain dan layout yang tepat untuk membuat tampilan portfolio menarik, termasuk platform digital untuk memudahkan pembuatan portfolio online.`
      }, 
    ]
  }
  